name: Deploy to GCP

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/<TU_PROYECTO_ID>/locations/global/workloadIdentityPools/<TU_POOL_ID>
          service_account: <TU_CUENTA_DE_SERVICIO>@<TU_PROYECTO_ID>.iam.gserviceaccount.com
      - name: Build the Docker image
        run: docker build -t gcr.io/$PROJECT_ID/$TAG:$COMMIT_SHA .
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          COMMIT_SHA: ${{ github.sha }}
      - name: Push the image to Google Container Registry
        run: docker push gcr.io/$PROJECT_ID/$TAG:$COMMIT_SHA
      - name: Deploy to Cloud Run
        run: gcloud run deploy --image gcr.io/$PROJECT_ID/$TAG:$COMMIT_SHA --service my-service
